# Generated by Django 2.2.4 on 2019-08-23 13:41

import apps.bhs.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='UNKNOWN', editable=False, help_text='\n            The name of the resource.\n        ', max_length=255)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], default=0, editable=False, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('kind', models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')])], editable=False, help_text='\n            The kind of group.\n        ')),
                ('gender', models.IntegerField(choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], default=10, editable=False, help_text='\n            The gender of group.\n        ')),
                ('district', models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], editable=False, null=True)),
                ('division', models.IntegerField(blank=True, choices=[('EVG', [(10, 'EVG Division I'), (20, 'EVG Division II'), (30, 'EVG Division III'), (40, 'EVG Division IV'), (50, 'EVG Division V')]), ('FWD', [(60, 'FWD Arizona'), (70, 'FWD Northeast'), (80, 'FWD Northwest'), (90, 'FWD Southeast'), (100, 'FWD Southwest')]), ('LOL', [(110, 'LOL 10000 Lakes'), (120, 'LOL Division One'), (130, 'LOL Northern Plains'), (140, 'LOL Packerland'), (150, 'LOL Southwest')]), ('MAD', [(170, 'MAD Central'), (180, 'MAD Northern'), (190, 'MAD Southern')]), ('NED', [(210, 'NED Granite and Pine'), (220, 'NED Mountain'), (230, 'NED Patriot'), (240, 'NED Sunrise'), (250, 'NED Yankee')]), ('SWD', [(260, 'SWD Northeast'), (270, 'SWD Northwest'), (280, 'SWD Southeast'), (290, 'SWD Southwest')])], editable=False, null=True)),
                ('bhs_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('code', models.CharField(blank=True, default='', editable=False, help_text='\n            Short-form code.', max_length=255)),
                ('website', models.URLField(blank=True, default='', editable=False, help_text='\n            The website URL of the resource.')),
                ('email', apps.bhs.fields.LowerEmailField(blank=True, editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', editable=False, help_text='\n            The phone number of the resource.  Include country code.', max_length=128, region=None)),
                ('fax_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', editable=False, help_text='\n            The fax number of the resource.  Include country code.', max_length=128, region=None)),
                ('start_date', models.DateField(blank=True, editable=False, null=True)),
                ('end_date', models.DateField(blank=True, editable=False, null=True)),
                ('location', models.CharField(blank=True, default='', help_text='\n            The geographical location of the resource.', max_length=255)),
                ('facebook', models.URLField(blank=True, default='', editable=False, help_text='\n            The facebook URL of the resource.')),
                ('twitter', models.URLField(blank=True, default='', editable=False, help_text='\n            The twitter URL of the resource.')),
                ('youtube', models.URLField(blank=True, default='', editable=False, help_text='\n            The youtube URL of the resource.')),
                ('pinterest', models.URLField(blank=True, default='', editable=False, help_text='\n            The pinterest URL of the resource.')),
                ('flickr', models.URLField(blank=True, default='', editable=False, help_text='\n            The flickr URL of the resource.')),
                ('instagram', models.URLField(blank=True, default='', editable=False, help_text='\n            The instagram URL of the resource.')),
                ('soundcloud', models.URLField(blank=True, default='', editable=False, help_text='\n            The soundcloud URL of the resource.')),
                ('image', models.ImageField(blank=True, default='', upload_to=apps.bhs.fields.ImageUploadPath('image'))),
                ('description', models.TextField(blank=True, default='', help_text='\n            A description of the group.  Max 1000 characters.', max_length=1000)),
                ('visitor_information', models.TextField(blank=True, default='', editable=False, max_length=255)),
                ('participants', models.CharField(blank=True, default='', help_text='Director(s) or Members (listed TLBB)', max_length=255)),
                ('chapters', models.CharField(blank=True, default='', help_text='\n            The denormalized chapter group.', max_length=255)),
                ('notes', models.TextField(blank=True, default='', help_text='\n            Notes (for internal use only).')),
                ('is_senior', models.BooleanField(blank=True, default=False, help_text='Qualifies as a Senior Group.  Must be set manually.')),
                ('is_youth', models.BooleanField(blank=True, default=False, help_text='Qualifies as a Youth Group.  Must be set manually.')),
                ('tree_sort', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('owners', models.ManyToManyField(blank=True, editable=False, related_name='groups', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bhs.Group')),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'ordering': ['tree_sort'],
                'unique_together': {('bhs_id', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10, editable=False, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('prefix', models.CharField(blank=True, default='', editable=False, help_text='\n            The prefix of the person.', max_length=255)),
                ('first_name', models.CharField(editable=False, help_text='\n            The first name of the person.', max_length=255)),
                ('middle_name', models.CharField(blank=True, default='', editable=False, help_text='\n            The middle name of the person.', max_length=255)),
                ('last_name', models.CharField(editable=False, help_text='\n            The last name of the person.', max_length=255)),
                ('nick_name', models.CharField(blank=True, default='', editable=False, help_text='\n            The nickname of the person.', max_length=255)),
                ('suffix', models.CharField(blank=True, default='', editable=False, help_text='\n            The suffix of the person.', max_length=255)),
                ('birth_date', models.DateField(blank=True, editable=False, null=True)),
                ('spouse', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', help_text='\n            The geographical location of the resource.', max_length=255)),
                ('part', models.IntegerField(blank=True, choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], editable=False, null=True)),
                ('mon', models.IntegerField(blank=True, editable=False, help_text='\n            Men of Note.', null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female')], editable=False, null=True)),
                ('is_deceased', models.BooleanField(blank=True, default=False, editable=False)),
                ('is_honorary', models.BooleanField(blank=True, default=False, editable=False)),
                ('is_suspended', models.BooleanField(blank=True, default=False, editable=False)),
                ('is_expelled', models.BooleanField(blank=True, default=False, editable=False)),
                ('email', apps.bhs.fields.LowerEmailField(blank=True, editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='', editable=False, help_text='\n            The complete address of the resource.', max_length=1000)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The home phone number of the resource.  Include country code.', max_length=128, region=None)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The work phone number of the resource.  Include country code.', max_length=128, region=None)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(editable=False, help_text='\n            The cell phone number of the resource.  Include country code.', max_length=128, region=None)),
                ('airports', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=3), blank=True, null=True, size=None)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.bhs.fields.ImageUploadPath('image'))),
                ('description', models.TextField(blank=True, default='', help_text='\n            A bio of the person.  Max 1000 characters.', max_length=1000)),
                ('notes', models.TextField(blank=True, default='', help_text='\n            Notes (for internal use only).')),
                ('bhs_id', models.IntegerField(editable=False, unique=True)),
                ('current_through', models.DateField(blank=True, editable=False, null=True)),
                ('owners', models.ManyToManyField(blank=True, editable=False, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('office', models.IntegerField(choices=[(10, 'SCJC'), (20, 'DRCJ'), (30, 'CA'), (40, 'Judge'), (50, 'Manager'), (60, 'Librarian')])),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='bhs.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='bhs.Person')),
            ],
            options={
                'verbose_name_plural': 'Officers',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=0, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.')),
                ('part', models.IntegerField(blank=True, choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bhs.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bhs.Person')),
            ],
            options={
                'verbose_name_plural': 'Members',
                'unique_together': {('group', 'person')},
            },
        ),
    ]
