# Generated by Django 2.2.3 on 2019-08-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Structure',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
