# Generated by Django 2.2.4 on 2019-08-08 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bhs', '0002_auto_20190807_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mc_pk',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mc_pk',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='mc_pk',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mc_pk',
        ),
        migrations.AddField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
