# Generated by Django 2.2.4 on 2019-08-28 19:13

from django.conf import settings
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0002_auto_20190828_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            Short-form chapter code.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='gender',
            field=models.IntegerField(choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet')])], editable=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='UNKNOWN', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(blank=True, editable=False, help_text='\n            These are the active officers with active accounts.\n        ', related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], default=0, editable=False),
        ),
    ]
