# Generated by Django 2.2.4 on 2019-08-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0003_auto_20190808_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_through',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
