# Generated by Django 2.2.4 on 2019-08-19 19:01

import apps.bhs.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0004_person_current_through'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='district',
        ),
        migrations.RemoveField(
            model_name='person',
            name='website',
        ),
        migrations.AlterField(
            model_name='group',
            name='gender',
            field=models.IntegerField(choices=[(10, 'Male'), (20, 'Female'), (30, 'Mixed')], default=10, editable=False, help_text='\n            The gender of group.\n        '),
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[('International', [(1, 'International')]), ('District', [(11, 'District'), (12, 'Noncompetitive'), (13, 'Affiliate')]), ('Chapter', [(30, 'Chapter')]), ('Group', [(32, 'Chorus'), (41, 'Quartet'), (46, 'VLQ')])], editable=False, help_text='\n            The kind of group.\n        '),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='UNKNOWN', editable=False, help_text='\n            The name of the resource.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (-5, 'AIC'), (0, 'New'), (10, 'Active')], default=0, editable=False, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, default='', editable=False, help_text='\n            The complete address of the resource.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='airports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=3), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='bhs_id',
            field=models.IntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=apps.bhs.fields.LowerEmailField(blank=True, editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(10, 'Male'), (20, 'Female')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_deceased',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_expelled',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_honorary',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_suspended',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            The middle name of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='mon',
            field=models.IntegerField(blank=True, editable=False, help_text='\n            Men of Note.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            The nickname of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='owners',
            field=models.ManyToManyField(blank=True, editable=False, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='part',
            field=models.IntegerField(blank=True, choices=[(1, 'Tenor'), (2, 'Lead'), (3, 'Baritone'), (4, 'Bass')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            The prefix of the person.', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='representing',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(-10, 'Inactive'), (0, 'New'), (10, 'Active')], default=10, editable=False, help_text='DO NOT CHANGE MANUALLY unless correcting a mistake.  Use the buttons to change state.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            The suffix of the person.', max_length=255),
        ),
    ]
