# Generated by Django 2.2.4 on 2019-08-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0005_auto_20190819_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='representing',
        ),
    ]
