# Generated by Django 2.2.4 on 2019-08-19 19:47

import apps.bhs.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bhs', '0006_remove_person_representing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='district',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_divided',
        ),
        migrations.AlterField(
            model_name='group',
            name='bhs_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='chapters',
            field=models.CharField(blank=True, default='', help_text='\n            The denormalized chapter group.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(blank=True, default='', editable=False, help_text='\n            Short-form code.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', help_text='\n            A description of the group.  Max 1000 characters.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='group',
            name='division',
            field=models.IntegerField(blank=True, choices=[('EVG', [(10, 'EVG Division I'), (20, 'EVG Division II'), (30, 'EVG Division III'), (40, 'EVG Division IV'), (50, 'EVG Division V')]), ('FWD', [(60, 'FWD Arizona'), (70, 'FWD Northeast'), (80, 'FWD Northwest'), (90, 'FWD Southeast'), (100, 'FWD Southwest')]), ('LOL', [(110, 'LOL 10000 Lakes'), (120, 'LOL Division One'), (130, 'LOL Northern Plains'), (140, 'LOL Packerland'), (150, 'LOL Southwest')]), ('MAD', [(170, 'MAD Central'), (180, 'MAD Northern'), (190, 'MAD Southern')]), ('NED', [(210, 'NED Granite and Pine'), (220, 'NED Mountain'), (230, 'NED Patriot'), (240, 'NED Sunrise'), (250, 'NED Yankee')]), ('SWD', [(260, 'SWD Northeast'), (270, 'SWD Northwest'), (280, 'SWD Southeast'), (290, 'SWD Southwest')])], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='email',
            field=apps.bhs.fields.LowerEmailField(blank=True, editable=False, help_text='\n            The contact email of the resource.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='facebook',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The facebook URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='fax_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', editable=False, help_text='\n            The fax number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='flickr',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The flickr URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=apps.bhs.fields.ImageUploadPath('image')),
        ),
        migrations.AlterField(
            model_name='group',
            name='instagram',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The instagram URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_senior',
            field=models.BooleanField(blank=True, default=False, help_text='Qualifies as a Senior Group.  Must be set manually.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_youth',
            field=models.BooleanField(blank=True, default=False, help_text='Qualifies as a Youth Group.  Must be set manually.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, default='', help_text='\n            The geographical location of the resource.', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='\n            Notes (for internal use only).'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owners',
            field=models.ManyToManyField(blank=True, editable=False, related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bhs.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', editable=False, help_text='\n            The phone number of the resource.  Include country code.', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='group',
            name='pinterest',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The pinterest URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='representing',
            field=models.IntegerField(blank=True, choices=[(110, 'BHS'), (200, 'CAR'), (205, 'CSD'), (210, 'DIX'), (215, 'EVG'), (220, 'FWD'), (225, 'ILL'), (230, 'JAD'), (235, 'LOL'), (240, 'MAD'), (345, 'NED'), (350, 'NSC'), (355, 'ONT'), (360, 'PIO'), (365, 'RMD'), (370, 'SLD'), (375, 'SUN'), (380, 'SWD')], editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='soundcloud',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The soundcloud URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='twitter',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The twitter URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='visitor_information',
            field=models.TextField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='website',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The website URL of the resource.'),
        ),
        migrations.AlterField(
            model_name='group',
            name='youtube',
            field=models.URLField(blank=True, default='', editable=False, help_text='\n            The youtube URL of the resource.'),
        ),
    ]
